CONFIG_SERIAL=y
CONFIG_LOG=y
CONFIG_MCUBOOT_LOG_LEVEL_DBG=y


CONFIG_MULTITHREADING=y
CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_BOOT_MAX_IMG_SECTORS=512


CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
CONFIG_NORDIC_QSPI_NOR=n 
CONFIG_GPIO=y
