CONFIG_MQTT_HELPER=y
CONFIG_MQTT_HELPER_NATIVE_TLS=y
CONFIG_MQTT_HELPER_PORT=8883
CONFIG_MQTT_HELPER_SEC_TAG=24
CONFIG_MQTT_HELPER_PROVISION_CERTIFICATES=y
CONFIG_MQTT_HELPER_CERTIFICATES_FOLDER="certificates"