#https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/releases_and_maturity/migration/migration_sysbuild.html
SB_CONFIG_BOOTLOADER_MCUBOOT=y
# Signing key
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${APPLICATION_CONFIG_DIR}/priv.pem"
# Place secondary slot in external flash
SB_CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=y
# Allow SPI NOR driver to be used for the external memory region
SB_CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y

